### ISSUE TITLE
Bukkit support when?

### ISSUE THREAD

**Issue by greysilly7** [hYdos/A-Mistake#1]

**Comment by QPCrummer** [comment]
🅱️ukkit

**Comment by greysilly7** [comment]
Bukkit makes the world go around

**Comment by nevetS-718** [comment]
A real mistake would include bukkit and sponge

**Comment by QPCrummer** [comment]
No no, a real mistake would be including Paper as a whole

**Comment by QPCrummer** [comment]
Let’s make Yatopia++

**Comment by greysilly7** [comment]
Don't forget about sugarcane lel

**Comment by QPCrummer** [comment]
_when all of the sugarcane devs convert to fabric_

**Comment by supsm** [comment]
Hi qpcrummer

**Comment by QPCrummer** [comment]
Hi supsm

**Comment by supsm** [comment]
:holpme:

**Comment by QPCrummer** [comment]
:holpmetoo:

**Comment by hYdos** [comment]
stop conc
